#/home/ubuntu/multiturn_ver1/new crawler/config/site_config.py

SITES = {
    "ACADEMIC_NOTICE": {
        "base_url": "https://www.yonsei.ac.kr/sc/support/notice.jsp",
        "start_url": "https://www.yonsei.ac.kr/sc/support/notice.jsp?mode=view&article_no=244053&board_wrapper=%2Fsc%2Fsupport%2Fnotice.jsp&pager.offset=0&board_no=15",
        "url_number": "article_no",
        "title_selector": "dl.board_view dt strong",
        "date_selector": ".date",
        "author_selector": "span.title",
        "sub_category_selector": "null",
        "content_selector": ".fr-view",
        "next_page_selector": "#jwxe_main_content > div.jwxe_board > div > ul > li:nth-child(1) > a",
    },
    "SCOLARSHIP" : {
        "base_url": "https://www.yonsei.ac.kr/sc/support/scholarship.jsp",
        "start_url": "https://www.yonsei.ac.kr/sc/support/scholarship.jsp?mode=view&article_no=243969&board_wrapper=%2Fsc%2Fsupport%2Fscholarship.jsp&pager.offset=0&board_no=29",
        "url_number": "article_no",
        "title_selector": "#jwxe_main_content > div.jwxe_board > div > dl > dt > strong",
        "date_selector": "#jwxe_main_content > div.jwxe_board > div > dl > dt > span",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div.jwxe_board > div > dl > dd",
        "next_page_selector": "#jwxe_main_content > div.jwxe_board > div > ul > li:nth-child(1) > a",
    },
    "ARCHITECTURE_ENGINEERING" :{
        "base_url": "https://arch.yonsei.ac.kr",
        "start_url": "https://arch.yonsei.ac.kr/notice",
        "url_number": None,
        "title_selector": "#body > div.dcore.dcore-view.dcore-notice > div.wrap-with-aside > div:nth-child(1) > div.dcore-body > h1#body > div.dcore.dcore-view.dcore-notice > div.wrap-with-aside > div:nth-child(1) > div.dcore-body > h1",
        "date_selector": "null",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#body > div.dcore.dcore-view.dcore-notice > div.wrap-with-aside > div:nth-child(1) > div.post-body",
        "next_page_selector": "null",
    },
    "MATERIALS_SCIENCE_ENGINEERING" : {
        "base_url": "https://mse.yonsei.ac.kr/",
        "start_url": "https://mse.yonsei.ac.kr/board/board.php?bo_table=notice&cate=undergraduate&pg=2&idx=139",
        "url_number": "idx",
        "title_selector": "#main > div.section.section1 > div > div.top > strong",
        "date_selector": "#main > div.section.section1 > div > div.top > span",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#main > div.section.section1 > div > div.con",
        "next_page_selector": "null",
    },
    "SONGDO_DORM" : {
        "base_url": "https://yicdorm.yonsei.ac.kr",
        "start_url": "https://yicdorm.yonsei.ac.kr/board.asp?act=view&mid=m05_01&bid=1&cmid=m05_01&page=1&idx=43000&keyword=&lang=k",
        "url_number": "idx",
        "title_selector": "#BBSBoardViewTitle > span.BBSTitle",
        "date_selector": "#BBSBoardViewDate2",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#boardcontent",
        "next_page_selector": "#BBSBoardViewPrev > span.BBSTitle2 > a",
    },
    "RC_EDUCATION": {
        "base_url": "https://yicrc.yonsei.ac.kr",
        "start_url": "https://yicrc.yonsei.ac.kr/main/news.asp?act=view&mid=m06_01&bid=11&cmid=m06_01&page=3&idx=1560",
        "url_number": "idx",
        "title_selector": ".BoardWrapper #BoardViewTitle",
        "date_selector": "#BoardViewAdd",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#BoardContent",
        "next_page_selector": "#BoardViewPreOnly > span.LableP > a",
    },
    "MAIN_DORM" : {
        "base_url": "https://dorm.yonsei.ac.kr/",
        "start_url": "https://dorm.yonsei.ac.kr/board/?mode=V&idx=8680&id=notice&p=1",
        "url_number": "idx",
        "title_selector": "#mqSub-Data > div > h3",
        "date_selector": "#mqSub-Data > div > div.board-view-info > dl.writer > dd > span", 
        "author_selector": "#mqSub-Data > div > div.board-view-info > dl.writer > dd > b",
        "sub_category_selector": "#mqSub-Data > div > div.board-view > span",
        "content_selector": "#mqSub-Data > div > div.board-view > div",
        "next_page_selector": "null",
    },
    "INTERNATIONAL_OFFICE" : {
        "base_url": "https://oia.yonsei.ac.kr",
        "start_url": "https://oia.yonsei.ac.kr/news/newsIMain.asp?bidx=10557&page=&SFIELD=&GTXT=&gbn=A02&bgbn=R",
        "url_number": "bidx",
        "title_selector": "#contRight > div > div > div.content > div > ul.bbsLayout_view > li.title_view > h4",
        "date_selector": "#contRight > div > div > div.content > div > ul.bbsLayout_view > li.title_view > div > span.date_txt",
        "author_selector": "#contRight > div > div > div.content > div > ul.bbsLayout_view > li.title_view > div > span.admin_txt",
        "sub_category_selector": "null",
        "content_selector": "#contRight > div > div > div.content > div > ul.bbsLayout_view > li:nth-child(2) > div",
        "next_page_selector": "#contRight > div > div > div.content > div > ul.prev_next_list > li:nth-child(2) > div > h4 > a",
    },
    "BUSINESS_COLLEGE": {
            "base_url": "https://ysb.yonsei.ac.kr",
            "start_url": "https://ysb.yonsei.ac.kr/board.asp?act=view&mid=m06%5F01&cmid=m06%5F01&cid=0&eid=&bgn=&bid=7&sOpt=&pact=&mType=&mCourse=&mKisu=&tabidx=&hSel=&page=1&keyword=&uid=&idx=8025",
            "url_number": "idx",
            "title_selector": "#BoardViewTitle",
            "date_selector": "#BoardViewAdd",
            "author_selector": "null",
            "sub_category_selector": "null",
            "content_selector": "#BoardContent",
            "next_page_selector": "#BoardViewPreOnly > span.LableP > a",
        },
    "INTERNATIONAL_COLLEGE_STUDENT_SERVICES" : {
        "base_url": "https://uic.yonsei.ac.kr",
        "start_url": "https://uic.yonsei.ac.kr/main/news.asp?act=list&mid=m06_01_03",
        "url_number": "idx",
        "title_selector": "#BoardViewTitle",
        "date_selector": "#BoardViewAdd",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#BoardContent",
        "next_page_selector": "null",
    },
    "INTERNATIONAL_COLLEGE_ACADEMIC_AFFAIRS" : {
        "base_url": "https://uic.yonsei.ac.kr",
        "start_url": "https://uic.yonsei.ac.kr/main/news.asp?act=list&mid=m06_01_02",
        "url_number": "idx",
        "title_selector": "#BoardViewTitle",
        "date_selector": "#BoardViewAdd",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#BoardContent",
        "next_page_selector": "null",
    },
    "ATMOSPHERIC_SCIENCE" : {
        "base_url": "https://atmos.yonsei.ac.kr",
        "start_url": "https://atmos.yonsei.ac.kr/categories/%EA%B3%B5%EC%A7%80%EC%82%AC%ED%95%AD/page/2/",
        "url_number": None,
        "title_selector": "#heading-breadcrumbs > div > div > div > h1",
        "date_selector": "#blog-post > p",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#post-content",
        "next_page_selector": "null",
    },
    "SOCIOLOGY": {
            "base_url": "https://sociology.yonsei.ac.kr",
            "start_url": "https://sociology.yonsei.ac.kr/elementor-2080/?mod=document&pageid=1&uid=277",
            "url_number": "uid",
            "title_selector": "#kboard-default-document > div.kboard-document-wrap > div.kboard-title > h1",
            "date_selector": "#kboard-default-document > div.kboard-document-wrap > div.kboard-detail > div.detail-attr.detail-date > div.detail-value",
            "author_selector": "#kboard-default-document > div.kboard-document-wrap > div.kboard-detail > div.detail-attr.detail-writer > div.detail-value",
            "sub_category_selector": "null",
            "content_selector": "#kboard-default-document > div.kboard-document-wrap > div.kboard-content > div.content-view",
            "next_page_selector": "#kboard-default-document > div.kboard-document-navi > div.kboard-next-document > a",
        },
    "CHEMICAL_ENGINEERING": {
            "base_url": "https://chemeng.yonsei.ac.kr",
            "start_url": "https://chemeng.yonsei.ac.kr/?c=209&s=209&gp=1&gbn=viewok&ix=2735",
            "url_number": "ix",
            "title_selector": "#bbsView > div.bbs-view-head > h3",
            "date_selector": "#bbsView > div.bbs-view-head > div > ul > li:nth-child(2) > strong",
            "author_selector": "#bbsView > div.bbs-view-head > div > ul > li:nth-child(1) > strong",
            "sub_category_selector": "null",
            "content_selector": "#bbsContents",
            "next_page_selector": "#sub > section.sub__contents.animsition > div.sub__content > div:nth-child(2) > div.list_btn > div.top > a",
        },
    "CHEMISTRY" : {
        "base_url": "https://chemyonsei.kr",
        "start_url": "https://chemyonsei.kr/board/notice/100125",
        "url_number": None,
        "title_selector": "#wrap > main > article > section > div > div > div > div.nxb-view__header > div > h3",
        "date_selector": "#wrap > main > article > section > div > div > div > div.nxb-view__header > div > ul > li > span > time",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#wrap > main > article > section > div > div > div > div.nxb-view__contents.text-small",
        "next_page_selector": "#wrap > main > article > section > div > div > div > div.nxb-view__footer > div > div.nxb-view__related-wrap.prev > div > a",
    },
    "EARTH_SYSTEM_SCIENCE" : {
        "base_url": "http://geo.yonsei.ac.kr/index.php?",
        "start_url": "http://geo.yonsei.ac.kr/index.php?page=view&pg=&idx=1488&hCode=BOARD&bo_idx=2&sfl=&stx=#",
        "url_number": "idx",
        "title_selector": "#con_area > table > thead > tr:nth-child(1) > th",
        "date_selector": "#con_area > table > thead > tr:nth-child(2) > td > ul > li:nth-child(5)",
        "author_selector": "#con_area > table > thead > tr:nth-child(2) > td > ul > li:nth-child(1)",
        "sub_category_selector": "null",
        "content_selector": "#con_area > table > tbody > tr > td > div",
        "next_page_selector": "#con_area > table > tfoot > tr:nth-child(2) > td:nth-child(2) > a",
    },
    "DENTAL": {
        "base_url": "https://dentistry.yonsei.ac.kr/dentistry/news/notice.do",
        "start_url": "https://dentistry.yonsei.ac.kr/dentistry/news/notice.do?mode=view&articleNo=124354&article.offset=0&articleLimit=12",
        "url_number": "articleNo",
        "title_selector": ".container .article-header .subject-area .subject",
        "date_selector": ".container .article-header .subject-area .article-info .item.date",
        "author_selector": ".container .article-header .subject-area .article-info .item.name",
        "sub_category_selector": "null",
        "content_selector": ".container .article-body .fr-view",
        "next_page_selector": ".article-nav .next a"
    },
    "NURSING": {
        "base_url": "https://nursingcollege.yonsei.ac.kr/nursing/news/notice/academic.do",
        "start_url": "https://nursingcollege.yonsei.ac.kr/nursing/news/notice/academic.do?mode=view&articleNo=124553&article.offset=0&articleLimit=12",
        "url_number": "articleNo",
        "title_selector": ".container .article-header .subject-area .subject",
        "date_selector": ".container .article-header .subject-area .article-info .item.date",
        "author_selector": ".container .article-header .subject-area .article-info .item.name",
        "sub_category_selector": "null",
        "content_selector": ".container .article-body .fr-view",
        "next_page_selector": ".article-nav .next a"
    },
    "MEDICAL": {
        "base_url": "https://medicine.yonsei.ac.kr/medicine/news/notice.do",
        "start_url": "https://medicine.yonsei.ac.kr/medicine/news/notice.do?&mode=view&articleNo=124499&articleLimit=12",
        "url_number": "articleNo",
        "title_selector": ".container .article-header .subject-area .subject",
        "date_selector": ".container .article-header .subject-area .article-info .item.date",
        "author_selector": ".container .article-header .subject-area .article-info .item.name",
        "sub_category_selector": "null",
        "content_selector": ".container .article-body .fr-view",
        "next_page_selector": ".article-nav .next a"
    },
    "AI_CONVERGENCE_COLLEGE": {
        "base_url": "https://computing.yonsei.ac.kr/bbs/",
        "start_url": "https://computing.yonsei.ac.kr/bbs/board.php?bo_table=sub4_4&wr_id=122",
        "url_number": "wr_id",
        "title_selector": "#bo_v_title > span.bo_v_tit", 
        "date_selector": "#bo_v_info > strong.if_date",
        "author_selector": "#bo_v_info > strong:nth-child(3) > span",
        "sub_category_selector": "null",
        "content_selector": "#bo_v_con",
        "next_page_selector": "#bo_v_top > ul.bo_v_nb > li.btn_prv > a",
    },
    "ARTIFICIAL_INTELLIGENCE": {
        "base_url": "https://ai.yonsei.ac.kr/bbs/",
        "start_url": "https://ai.yonsei.ac.kr/bbs/board.php?bo_table=sub5_1&wr_id=308",
        "url_number": "wr_id",
        "title_selector": "#bo_v_title > span.bo_v_tit", 
        "date_selector": "#bo_v_info > strong.if_date",
        "author_selector": "#bo_v_info > strong:nth-child(3) > span",
        "sub_category_selector": "null",
        "content_selector": "#bo_v_con",
        "next_page_selector": "#bo_v_top > ul.bo_v_nb > li.btn_prv > a",
    },
    "ADVANCED_COMPUTING": {
        "base_url": "https://devcms.yonsei.ac.kr/csai/board/facultyBoard.do",
        "start_url": "https://devcms.yonsei.ac.kr/csai/board/facultyBoard.do?mode=view&articleNo=218019&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(4) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "sub_category_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v1 > dd",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    }, 
    "COMPUTER_SCIENCE": {
        "base_url": "https://cs.yonsei.ac.kr/bbs/",
        "start_url": "https://cs.yonsei.ac.kr/bbs/board.php?bo_table=sub5_1&wr_id=526&page=1",
        "url_number": "wr_id",
        "title_selector": "#bo_v_title > span.bo_v_tit",
        "date_selector": "#bo_v_info > strong.if_date",
        "author_selector": "#bo_v_info > strong:nth-child(3) > span",
        "sub_category_selector": "null",
        "content_selector": "#bo_v_con",
        "next_page_selector": "#bo_v_top > ul.bo_v_nb > li.btn_prv > a",
    },
    "ADVANCED_CONVERGENCE_ENGINEERING": {
        "base_url": "https://sit.yonsei.ac.kr/sit/community/notice.do",
        "start_url": "https://sit.yonsei.ac.kr/sit/community/notice.do?mode=view&articleNo=216672&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "null",
    },
    "ECONOMICS": {
        "base_url": "https://economics.yonsei.ac.kr/economics/community/under_notice.do",
        "start_url": "https://economics.yonsei.ac.kr/economics/community/under_notice.do?mode=view&articleNo=218126&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "LITERATURE_COLLEGE" :{
        "base_url": "https://libart.yonsei.ac.kr/libart/board/notice.do",
        "start_url": "https://libart.yonsei.ac.kr/libart/board/notice.do?mode=view&articleNo=216674&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "ECONOMICS_COLLEGE" : {
        "base_url": "https://yce.yonsei.ac.kr/ybe/notice/notice.do",
        "start_url": "https://yce.yonsei.ac.kr/ybe/notice/notice.do?mode=view&articleNo=189198&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "BUSINESS_SCHOOL" :{
        "base_url": "https://msb.yonsei.ac.kr/msb/community/notice.do",
        "start_url": "https://msb.yonsei.ac.kr/msb/community/notice.do?mode=view&articleNo=64924&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "ENGINEERING_COLLEGE" : {
        "base_url": "https://engineering.yonsei.ac.kr/engineering/board/notice.do",
        "start_url": "https://engineering.yonsei.ac.kr/engineering/board/notice.do?mode=view&articleNo=217942&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "LIFE_SYSTEMS_COLLEGE" :{
        "base_url": "https://bio.yonsei.ac.kr/bio/board/notice.do",
        "start_url": "https://bio.yonsei.ac.kr/bio/board/notice.do?mode=view&articleNo=188429&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "THEOLOGY_COLLEGE" :{
        "base_url": "https://yonshin.yonsei.ac.kr/theology/board02/undergraduate.do",
        "start_url": "https://yonshin.yonsei.ac.kr/theology/board02/undergraduate.do?mode=view&articleNo=216437&article.offset=0&articleLimit=10#/list",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "SOCIAL_SCIENCES_COLLEGE" :{
        "base_url": "https://socsci.yonsei.ac.kr/socsci/community/notice.do",
        "start_url": "https://socsci.yonsei.ac.kr/socsci/community/notice.do?mode=view&articleNo=213332&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "MUSIC_COLLEGE" :{
        "base_url": "https://music.yonsei.ac.kr/music/notice1.do",
        "start_url": "https://music.yonsei.ac.kr/music/notice1.do?mode=view&articleNo=218342&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "EDUCATION_SCIENCES_COLLEGE" :{
        "base_url": "https://ysces.yonsei.ac.kr/yses/edu/notice.do",
        "start_url": "https://ysces.yonsei.ac.kr/yses/edu/notice.do?mode=view&articleNo=209267&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "UNDERGRADUATE_COLLEGE" : {
        "base_url": "https://universitycollege.yonsei.ac.kr/fresh/infomation/student.do",
        "start_url": "https://universitycollege.yonsei.ac.kr/fresh/infomation/student.do?mode=view&articleNo=216980&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "SPORTS_APPLIED_INDUSTRY" : {
        "base_url": "https://sportindustrystudies.yonsei.ac.kr/ysis/college/college05.do",
        "start_url": "https://sportindustrystudies.yonsei.ac.kr/ysis/college/college05.do?mode=view&articleNo=191033&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "KOREAN_LANGUAGE_LITERATURE": {
        "base_url": "https://koreanlit.yonsei.ac.kr/korean/notice01.do",
        "start_url": "https://koreanlit.yonsei.ac.kr/korean/notice01.do?mode=view&articleNo=164239&article.offset=40&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "ENGLISH_LANGUAGE_LITERATURE": {
        "base_url": "https://ysenglish.yonsei.ac.kr/ysenglish/process/process.do",
        "start_url": "https://ysenglish.yonsei.ac.kr/ysenglish/process/process.do?mode=view&articleNo=160631&article.offset=10&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "GERMAN_LANGUAGE_LITERATURE": {
        "base_url": "https://ysgerman.yonsei.ac.kr/ysgerman/ger_notice.do",
        "start_url": "https://ysgerman.yonsei.ac.kr/ysgerman/ger_notice.do?mode=view&articleNo=216832&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "FRENCH_LANGUAGE_LITERATURE": {
        "base_url": "https://franys.yonsei.ac.kr/franys/notice.do",
        "start_url": "https://franys.yonsei.ac.kr/franys/notice.do?mode=view&articleNo=217285&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "RUSSIAN_LANGUAGE_LITERATURE": {
        "base_url": "https://rus.yonsei.ac.kr/russia/borad_main.do",
        "start_url": "https://rus.yonsei.ac.kr/russia/borad_main.do?mode=view&articleNo=216655&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "CHINESE_LANGUAGE_LITERATURE": {
        "base_url": "https://ycll.yonsei.ac.kr/yonseicll/board01.do",
        "start_url": "https://ycll.yonsei.ac.kr/yonseicll/board01.do?mode=list&&articleLimit=10&article.offset=30",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div > div > dl:nth-child(4) > dd",
        "author_selector": "#jwxe_main_content > div > div > div > dl:nth-child(2) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "null",
    },
    "HISTORY": {
        "base_url": "https://history.yonsei.ac.kr/histroy/02_announce/notice.do",
        "start_url": "https://history.yonsei.ac.kr/histroy/02_announce/notice.do?mode=view&articleNo=214163&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "PHILOSOPHY": {
        "base_url": "https://philosophy.yonsei.ac.kr/cholhak/process/process.do",
        "start_url": "https://philosophy.yonsei.ac.kr/cholhak/process/process.do?mode=view&articleNo=216652&article.offset=0&articleLimit=10#/list",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "LIBRARY_INFORMATION_SCIENCE": {
        "base_url": "https://yslis.yonsei.ac.kr/doai/board/notice.do",
        "start_url": "https://yslis.yonsei.ac.kr/doai/board/notice.do?mode=view&articleNo=218330&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "EDUCATION": {
        "base_url": "https://edu.yonsei.ac.kr/edu/community/notice.do",
        "start_url": "https://edu.yonsei.ac.kr/edu/community/notice.do?mode=view&articleNo=215579&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "PUBLIC_ADMINISTRATION": {
        "base_url": "https://yupa.yonsei.ac.kr/yupa/notice/undergraduate.do",
        "start_url": "https://yupa.yonsei.ac.kr/yupa/notice/undergraduate.do?mode=view&articleNo=217443&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "MASS_COMMUNICATION": {
        "base_url": "https://comm.yonsei.ac.kr/mcc/hgong.do",
        "start_url": "https://comm.yonsei.ac.kr/mcc/hgong.do?mode=view&articleNo=217021&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "SOCIAL_WELFARE": {
        "base_url": "https://welfare.yonsei.ac.kr/welfare/board/notice.do",
        "start_url": "https://welfare.yonsei.ac.kr/welfare/board/notice.do?mode=view&articleNo=216480&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "CULTURAL_ANTHROPOLOGY": {
        "base_url": "https://anthro.yonsei.ac.kr/anthro/board/board.do",
        "start_url": "https://anthro.yonsei.ac.kr/anthro/board/board.do?mode=view&articleNo=215779&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "LAW": {
        "base_url": "https://lawschool.yonsei.ac.kr/law/board/g_notice.do",
        "start_url": "https://lawschool.yonsei.ac.kr/law/board/g_notice.do?mode=view&articleNo=218601&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "MATHEMATICS": {
        "base_url": "https://math.yonsei.ac.kr/math/math/undergraduate_notice.do",
        "start_url": "https://math.yonsei.ac.kr/math/math/undergraduate_notice.do?mode=view&articleNo=186933&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "ASTRONOMY": {
        "base_url": "https://astro.yonsei.ac.kr/galaxy/galaxy01/notice.do",
        "start_url": "https://astro.yonsei.ac.kr/galaxy/galaxy01/notice.do?mode=view&articleNo=216531&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "INDUSTRY_ENGINEERING": {
        "base_url": "https://ie.yonsei.ac.kr/ie/community/under_notice.do",
        "start_url": "https://ie.yonsei.ac.kr/ie/community/under_notice.do?mode=view&articleNo=216430&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "SYSTEMS_BIOLOGY": {
        "base_url": "https://systemsbiology.yonsei.ac.kr/l_system/notice.do",
        "start_url": "https://systemsbiology.yonsei.ac.kr/l_system/notice.do?mode=view&articleNo=213587&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "BIOCHEMISTRY": {
        "base_url": "https://biochem.yonsei.ac.kr/biochem/board/board01.do",
        "start_url": "https://biochem.yonsei.ac.kr/biochem/board/board01.do?mode=view&articleNo=213543&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "BIOTECHNOLOGY": {
        "base_url": "https://biotech.yonsei.ac.kr/biotech/community/announce.do",
        "start_url": "https://biotech.yonsei.ac.kr/biotech/community/announce.do?mode=view&articleNo=217140&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "HUMAN_ECOLOGY": {
        "base_url": "https://che.yonsei.ac.kr/che/community_che/notice.do",
        "start_url": "https://che.yonsei.ac.kr/che/community_che/notice.do?mode=view&articleNo=216926&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "INTEGRATED_DESIGN": {
        "base_url": "https://che.yonsei.ac.kr/che/design/design_board.do",
        "start_url": "https://che.yonsei.ac.kr/che/design/design_board.do?mode=view&articleNo=213078&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "CHILD_FAMILY": {
        "base_url": "https://che.yonsei.ac.kr/che/child/child_board.do",
        "start_url": "https://che.yonsei.ac.kr/che/child/child_board.do?mode=view&articleNo=216925&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "INTERIOR_ARCHITECTURE": {
        "base_url": "https://che.yonsei.ac.kr/che/interior/interior_board.do",
        "start_url": "https://che.yonsei.ac.kr/che/interior/interior_board.do?mode=view&articleNo=169406&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "FOOD_NUTRITION": {
        "base_url": "https://che.yonsei.ac.kr/che/food/food_board.do",
        "start_url": "https://che.yonsei.ac.kr/che/food/food_board.do?mode=view&articleNo=215132&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "CLOTHING_ENVIRONMENT": {
        "base_url": "https://che.yonsei.ac.kr/che/departments/clothing_board.do",
        "start_url": "https://che.yonsei.ac.kr/che/departments/clothing_board.do?mode=view&articleNo=215282&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "THEOLOGY": {
        "base_url": "https://yonshin.yonsei.ac.kr/theology/board02/undergraduate.do",
        "start_url": "https://yonshin.yonsei.ac.kr/theology/board02/undergraduate.do?mode=view&articleNo=216439&article.offset=0&articleLimit=10#/list",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "PHARMACY": {
        "base_url": "https://pharmacy.yonsei.ac.kr/pharmacy/community/notice.do",
        "start_url": "https://pharmacy.yonsei.ac.kr/pharmacy/community/notice.do?mode=view&articleNo=216883&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "INTERDISCIPLINARY_MAJOR": {
        "base_url": "https://yongei.yonsei.ac.kr/yongei/community/notice.do",
        "start_url": "https://yongei.yonsei.ac.kr/yongei/community/notice.do?mode=view&articleNo=208947&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "#jwxe_main_content > div > div.txt-navi-wrap > dl:nth-child(2) > dd > a",
    },
    "MECHANICAL_ENGINEERING" : {
        "base_url": "https://me.yonsei.ac.kr/me/community/notice.do",
        "start_url": "https://me.yonsei.ac.kr/me/community/notice.do?mode=view&articleNo=213384&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "null",
    },
    "CIVIL_ENGINEERING": {
        "base_url": "https://civil.yonsei.ac.kr/civil/community/board_2.do",
        "start_url": "https://civil.yonsei.ac.kr/civil/community/board_2.do?mode=view&articleNo=216634&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "null",
    },
    "ELECTRICAL_ENGINEERING": {
        "base_url": "https://ee.yonsei.ac.kr/ee/community/academic_notice.do",
        "start_url": "https://ee.yonsei.ac.kr/ee/community/academic_notice.do?mode=view&articleNo=217262&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "null",
    },
    "URBAN_ENGINEERING": {
        "base_url": "https://urban.yonsei.ac.kr/urban/notice/notice.do",
        "start_url": "https://urban.yonsei.ac.kr/urban/notice/notice.do?mode=view&articleNo=218010&article.offset=0&articleLimit=10",
        "url_number": "articleNo",
        "title_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v01 > dd",
        "date_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(2) > dd",
        "author_selector": "#jwxe_main_content > div > div.board-wrap > div > dl:nth-child(3) > dd",
        "sub_category_selector": "null",
        "content_selector": "#jwxe_main_content > div > div.board-wrap > div > dl.board-write-box.board-write-box-v03 > dd",
        "next_page_selector": "null",
    },
    "GLOBAL_TALENT_COLLEGE" :{
        "base_url": "https://glc.yonsei.ac.kr",
        "start_url": "https://glc.yonsei.ac.kr/notice/?mod=document&uid=1698",
        "url_number": "uid",
        "title_selector": "#kboard-default-document > div.kboard-document-wrap > div.kboard-title > h1",
        "date_selector": "#kboard-default-document > div.kboard-document-wrap > div.kboard-detail > div.detail-attr.detail-date > div.detail-value",
        "author_selector": "#kboard-default-document > div.kboard-document-wrap > div.kboard-detail > div.detail-attr.detail-writer > div.detail-value",
        "sub_category_selector": "null",
        "content_selector": "#kboard-default-document > div.kboard-document-wrap > div.kboard-content > div",
        "next_page_selector": "#kboard-default-document > div.kboard-document-navi > div.kboard-next-document > a",
    },
    "SYSTEM_SEMICONDUCTOR_ENGINEERING" :{
        "base_url": "https://system.yonsei.ac.kr/bbs/",
        "start_url": "https://system.yonsei.ac.kr/bbs/board.php?bo_table=sub5_2_a&wr_id=76",
        "url_number": "wr_id",
        "title_selector": "#bo_v_title > span.bo_v_tit", 
        "date_selector": "#bo_v_info > strong.if_date",
        "author_selector": "#bo_v_info > strong:nth-child(3) > span",
        "sub_category_selector": "null",
        "content_selector": "#bo_v_con",
        "next_page_selector": "#bo_v_top > ul.bo_v_nb > li.btn_prv > a"
    },
    "DISPLAY_CONVERGENCE_ENGINEERING":{
        "base_url": "https://dis.yonsei.ac.kr/index.php",
        "start_url": "https://dis.yonsei.ac.kr/index.php?module=Board&action=SiteBoard&sMode=VIEW_FORM&iBrdNo=4&iBrdContNo=8&sBrdContRe=0&sSearchField=&sSearchValue=&CurrentPage=1",
        "url_number": "iBrdContNo",
        "title_selector": "#all_contents > div.sconts_wid > div.ibt_tab_v > div.ibt_v_top > div.ibt_v_top_tit",
        "date_selector": "#all_contents > div.sconts_wid > div.ibt_tab_v > div.ibt_v_top > div.ibt_v_top_txt > span:nth-child(2)",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#all_contents > div.sconts_wid > div.ibt_tab_v > div.ibt_v_ny",
        "next_page_selector": "#all_contents > div.sconts_wid > div.bot_lr_btn.clfix > div.bot_lf_btn > a:nth-child(2)",
    },
    "PHYSICAL_EDUCATION" :{
        "base_url": "https://ped.yonsei.ac.kr",
        "start_url": "https://ped.yonsei.ac.kr/board/departmentnews/article/168587",
        "url_number": None,
        "title_selector": "#wrap > div.container > div > div.col-lg-9 > h2",
        "date_selector": "#wrap > div.container > div > div.col-lg-9 > div.article-sub-info > div.article-date",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#wrap > div.container > div > div.col-lg-9 > div.content_p.domestic-article-contents",
        "next_page_selector": "#wrap > div.container > div > div.col-lg-9 > nav > div > div.col-xs-12.col-sm-6.bl > div > a",
    },
    "NATURAL_SCIENCES_COLLEGE" :{
        "base_url": "http://science.yonsei.ac.kr",
        "start_url": "http://science.yonsei.ac.kr/community/notice/300232",
        "url_number": None,
        "title_selector": "#offset-parent > section:nth-child(4) > div > div > div.nxb-default > div > div.nxb-view__header > h3",
        "date_selector": "#offset-parent > section:nth-child(4) > div > div > div.nxb-default > div > div.nxb-view__header > div.nxb-view__info > ul > li:nth-child(2) > div.nxb-view__info-dd",
        "author_selector": "null",
        "sub_category_selector": "null",
        "content_selector": "#offset-parent > section:nth-child(4) > div > div > div.nxb-default > div > div.nxb-view__contents",
        "next_page_selector": "#offset-parent > section:nth-child(4) > div > div > div.nxb-default > div > div.nxb-view__footer > div.nxb-view__related > div.nxb-view__related-desc.nxb-view__related-prev > div.nxb-view__related-txt-area > a",
    },
    "PHYSICS" :{
        "base_url": "https://physicsyonsei.kr",
        "start_url": "https://physicsyonsei.kr/notice/board/?type=view&idx=470",
        "url_number": "idx",
        "title_selector": "#board-view-default > div.bw_header > h3",
        "date_selector": "#board-view-default > div.bw_header > div > ul > li:nth-child(2) > span.dd",
        "author_selector": "#board-view-default > div.bw_header > div > ul > li:nth-child(1) > span.dd",
        "sub_category_selector": "null",
        "content_selector": "#board-view-default > div.bw_contents.editor_contents",
        "next_page_selector": "null",
    },
    "POLITICAL_SCIENCE": {
        "base_url": "http://politics.yonsei.ac.kr/",
        "start_url": "http://politics.yonsei.ac.kr/board_read.asp",
        "url_number": "page",
        "title_selector" : "table.table_com01.board_table_basic > tr:nth-child(3) > td > font > b",
        "date_selector": "table.table_com01.board_table_basic > tr:nth-child(1) > td.board_readTitle_td:nth-child(4) > font",
        "author_selector": "table.table_com01.board_table_basic > tr:nth-child(1) > td.board_readTitle_td:nth-child(2) > font",
        "sub_category_selector": "null",
        "content_selector": "table > tr > td > div > font.textplain",
        "next_page_selector": "null"
    },
    "PSYCHOLOGY": {
        "base_url": "https://psychsci.yonsei.ac.kr/",
        "start_url": "https://psychsci.yonsei.ac.kr/",
        "url_number": "page",
        "title_selector" : "C9DxTc",
        "date_selector": "",
        "author_selector": "",
        "sub_category_selector": "null",
        "content_selector": "oKdM2c ZZyype",
        "next_page_selector": "null"
    }
}
